url: https://zi-w.github.io
baseurl: 

# Site settings
title: Zi Wang's Homepage
email: ziw@mit.edu
description: "lala"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f0b9f7
  secondary: f799e7 
  secondary-dark: 6e6e99

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ziwang92
  - title: facebook
    url: https://www.facebook.com/violet.ziwang
  - title: linkedin
    url: https://www.linkedin.com/in/zeewang
  - title: bitbucket 
    url: http://bitbucket.org/zinnia
  - title: github
    url: http://github.com/zi-w

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty